## \Model\User REST routes
user_rest_list:
  url: /user
  method: 'get'
  action: '\Model\UserRest:listAction'
user_rest_get:
  url: /user/{id}
  method: 'get'
  action: '\Model\UserRest:getAction'
user_rest_post:
  url: /user
  method: 'post'
  action: '\Model\UserRest:postAction'
user_rest_put:
  url: /user/{id}
  method: 'put'
  action: '\Model\UserRest:putAction'
user_rest_put:
  url: /user/{id}
  method: 'patch'
  action: '\Model\UserRest:patchAction'
user_rest_put:
  url: /user/{id}
  method: 'delete'
  action: '\Model\UserRest:deleteAction'

## \Model\Group REST routes
group_rest_list:
  url: /group
  method: 'get'
  action: '\Model\GroupRest:listAction'
group_rest_get:
  url: /group/{id}
  method: 'get'
  action: '\Model\GroupRest:getAction'
group_rest_post:
  url: /group
  method: 'post'
  action: '\Model\GroupRest:postAction'
group_rest_put:
  url: /group/{id}
  method: 'put'
  action: '\Model\GroupRest:putAction'
group_rest_put:
  url: /group/{id}
  method: 'patch'
  action: '\Model\GroupRest:patchAction'
group_rest_put:
  url: /group/{id}
  method: 'delete'
  action: '\Model\GroupRest:deleteAction'

## \Model\AuthScope REST routes
auth_scope_rest_list:
  url: /auth_scope
  method: 'get'
  action: '\Model\AuthScopeRest:listAction'
auth_scope_rest_get:
  url: /auth_scope/{id}
  method: 'get'
  action: '\Model\AuthScopeRest:getAction'
auth_scope_rest_post:
  url: /auth_scope
  method: 'post'
  action: '\Model\AuthScopeRest:postAction'
auth_scope_rest_put:
  url: /auth_scope/{id}
  method: 'put'
  action: '\Model\AuthScopeRest:putAction'
auth_scope_rest_put:
  url: /auth_scope/{id}
  method: 'patch'
  action: '\Model\AuthScopeRest:patchAction'
auth_scope_rest_put:
  url: /auth_scope/{id}
  method: 'delete'
  action: '\Model\AuthScopeRest:deleteAction'

## \Model\GroupAuthScope REST routes
group_auth_scope_rest_list:
  url: /group_auth_scope
  method: 'get'
  action: '\Model\GroupAuthScopeRest:listAction'
group_auth_scope_rest_get:
  url: /group_auth_scope/{group_id}/{auth_scope_id}
  method: 'get'
  action: '\Model\GroupAuthScopeRest:getAction'
group_auth_scope_rest_post:
  url: /group_auth_scope
  method: 'post'
  action: '\Model\GroupAuthScopeRest:postAction'
group_auth_scope_rest_put:
  url: /group_auth_scope/{group_id}/{auth_scope_id}
  method: 'put'
  action: '\Model\GroupAuthScopeRest:putAction'
group_auth_scope_rest_put:
  url: /group_auth_scope/{group_id}/{auth_scope_id}
  method: 'patch'
  action: '\Model\GroupAuthScopeRest:patchAction'
group_auth_scope_rest_put:
  url: /group_auth_scope/{group_id}/{auth_scope_id}
  method: 'delete'
  action: '\Model\GroupAuthScopeRest:deleteAction'

## \Model\AuthClient REST routes
auth_client_rest_list:
  url: /auth_client
  method: 'get'
  action: '\Model\AuthClientRest:listAction'
auth_client_rest_get:
  url: /auth_client/{id}
  method: 'get'
  action: '\Model\AuthClientRest:getAction'
auth_client_rest_post:
  url: /auth_client
  method: 'post'
  action: '\Model\AuthClientRest:postAction'
auth_client_rest_put:
  url: /auth_client/{id}
  method: 'put'
  action: '\Model\AuthClientRest:putAction'
auth_client_rest_put:
  url: /auth_client/{id}
  method: 'patch'
  action: '\Model\AuthClientRest:patchAction'
auth_client_rest_put:
  url: /auth_client/{id}
  method: 'delete'
  action: '\Model\AuthClientRest:deleteAction'

## \Model\AuthToken REST routes
auth_token_rest_list:
  url: /auth_token
  method: 'get'
  action: '\Model\AuthTokenRest:listAction'
auth_token_rest_get:
  url: /auth_token/{token}
  method: 'get'
  action: '\Model\AuthTokenRest:getAction'
auth_token_rest_post:
  url: /auth_token
  method: 'post'
  action: '\Model\AuthTokenRest:postAction'
auth_token_rest_put:
  url: /auth_token/{token}
  method: 'put'
  action: '\Model\AuthTokenRest:putAction'
auth_token_rest_put:
  url: /auth_token/{token}
  method: 'patch'
  action: '\Model\AuthTokenRest:patchAction'
auth_token_rest_put:
  url: /auth_token/{token}
  method: 'delete'
  action: '\Model\AuthTokenRest:deleteAction'

## \Model\AuthCode REST routes
auth_code_rest_list:
  url: /auth_code
  method: 'get'
  action: '\Model\AuthCodeRest:listAction'
auth_code_rest_get:
  url: /auth_code/{auth_code}
  method: 'get'
  action: '\Model\AuthCodeRest:getAction'
auth_code_rest_post:
  url: /auth_code
  method: 'post'
  action: '\Model\AuthCodeRest:postAction'
auth_code_rest_put:
  url: /auth_code/{auth_code}
  method: 'put'
  action: '\Model\AuthCodeRest:putAction'
auth_code_rest_put:
  url: /auth_code/{auth_code}
  method: 'patch'
  action: '\Model\AuthCodeRest:patchAction'
auth_code_rest_put:
  url: /auth_code/{auth_code}
  method: 'delete'
  action: '\Model\AuthCodeRest:deleteAction'

## \Model\UserGroup REST routes
user_group_rest_list:
  url: /user_group
  method: 'get'
  action: '\Model\UserGroupRest:listAction'
user_group_rest_get:
  url: /user_group/
  method: 'get'
  action: '\Model\UserGroupRest:getAction'
user_group_rest_post:
  url: /user_group
  method: 'post'
  action: '\Model\UserGroupRest:postAction'
user_group_rest_put:
  url: /user_group/
  method: 'put'
  action: '\Model\UserGroupRest:putAction'
user_group_rest_put:
  url: /user_group/
  method: 'patch'
  action: '\Model\UserGroupRest:patchAction'
user_group_rest_put:
  url: /user_group/
  method: 'delete'
  action: '\Model\UserGroupRest:deleteAction'

